//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebJusticeIN.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string Aboutus_Menu {
            get {
                return ResourceManager.GetString("Aboutus_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justice Inn is a “Consortium of Legend Lawyers,” the first of its kind in Pakistan. Our team comprises of several legal dignitaries that have served on some of the highest legal positions in the country. From former Justices of Supreme Court and High courts of Pakistan and offices of an attorney general, Advocate general, Prosecutor general and our team has the aces of the sector.
        ///
        ///Apart from that, our legal and judicial team possess exceptional legal expertise. We do not provide piecemeal solutions but p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AbtUs_ParaText {
            get {
                return ResourceManager.GetString("AbtUs_ParaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOGS.
        /// </summary>
        public static string Blogs_Menu {
            get {
                return ResourceManager.GetString("Blogs_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL US AT.
        /// </summary>
        public static string Call_Us_At {
            get {
                return ResourceManager.GetString("Call_Us_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate of Excellence.
        /// </summary>
        public static string CertificateExcellence {
            get {
                return ResourceManager.GetString("CertificateExcellence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERTIFICATIONS.
        /// </summary>
        public static string Certifications_Menu {
            get {
                return ResourceManager.GetString("Certifications_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Custody.
        /// </summary>
        public static string ChildCustody {
            get {
                return ResourceManager.GetString("ChildCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Consultations.
        /// </summary>
        public static string ClientConsultation {
            get {
                return ResourceManager.GetString("ClientConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS FROM CLIENT.
        /// </summary>
        public static string ClientWords {
            get {
                return ResourceManager.GetString("ClientWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Court.
        /// </summary>
        public static string ConsumerCourt {
            get {
                return ResourceManager.GetString("ConsumerCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +92-321-4468358 | +92-42-37350687.
        /// </summary>
        public static string Contact_Numbers {
            get {
                return ResourceManager.GetString("Contact_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Now.
        /// </summary>
        public static string ContactNoBtn {
            get {
                return ResourceManager.GetString("ContactNoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        public static string ContactUs_Menu {
            get {
                return ResourceManager.GetString("ContactUs_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2019, All Right Reserved.
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Lawyers.
        /// </summary>
        public static string CorporateLawyers {
            get {
                return ResourceManager.GetString("CorporateLawyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal Matters.
        /// </summary>
        public static string CriminalMatters {
            get {
                return ResourceManager.GetString("CriminalMatters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTS.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT WE ARE EXPERT AT.
        /// </summary>
        public static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultancy.
        /// </summary>
        public static string Free_Consultancy {
            get {
                return ResourceManager.GetString("Free_Consultancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Online Legal.
        /// </summary>
        public static string Free_Online {
            get {
                return ResourceManager.GetString("Free_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home_Menu {
            get {
                return ResourceManager.GetString("Home_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour Rights.
        /// </summary>
        public static string LabourRights {
            get {
                return ResourceManager.GetString("LabourRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEST NEWS.
        /// </summary>
        public static string LatestNews_Menu {
            get {
                return ResourceManager.GetString("LatestNews_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law is complicate matter. It can cause you a big problem if you ignore it. Let us help you!.
        /// </summary>
        public static string LawComplication {
            get {
                return ResourceManager.GetString("LawComplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Negligence.
        /// </summary>
        public static string MedicalNegligence {
            get {
                return ResourceManager.GetString("MedicalNegligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAB references.
        /// </summary>
        public static string NABreferences {
            get {
                return ResourceManager.GetString("NABreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICE.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Divorce.
        /// </summary>
        public static string OnlineDivorce {
            get {
                return ResourceManager.GetString("OnlineDivorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Nikkah.
        /// </summary>
        public static string OnlineNikkah {
            get {
                return ResourceManager.GetString("OnlineNikkah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR COMPANY.
        /// </summary>
        public static string OurCompany {
            get {
                return ResourceManager.GetString("OurCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Assistance.
        /// </summary>
        public static string PoliceAssistance {
            get {
                return ResourceManager.GetString("PoliceAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional Attorneys.
        /// </summary>
        public static string ProfesionalAttorneys {
            get {
                return ResourceManager.GetString("ProfesionalAttorneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &amp; Land.
        /// </summary>
        public static string PropertyLand {
            get {
                return ResourceManager.GetString("PropertyLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ MORE.
        /// </summary>
        public static string ReadMore_btnText {
            get {
                return ResourceManager.GetString("ReadMore_btnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICES.
        /// </summary>
        public static string Services_Menu {
            get {
                return ResourceManager.GetString("Services_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Message.
        /// </summary>
        public static string SubmitMsg {
            get {
                return ResourceManager.GetString("SubmitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Cases.
        /// </summary>
        public static string SuccessfulCases {
            get {
                return ResourceManager.GetString("SuccessfulCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succession Certificate.
        /// </summary>
        public static string SuccessionCertificate {
            get {
                return ResourceManager.GetString("SuccessionCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial.
        /// </summary>
        public static string Testimonial {
            get {
                return ResourceManager.GetString("Testimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When young Katie Mitchell (Abbi Jacobson) heads on a road trip with her family.
        /// </summary>
        public static string TestimonialExample {
            get {
                return ResourceManager.GetString("TestimonialExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s important to have a competent legal team at your side at the time of dire need. Legal processes are not only a hassle because you don’t understand legal terminologies but because there also not many firms that provide unparalleled expertise and consultation..
        /// </summary>
        public static string WhyReason1 {
            get {
                return ResourceManager.GetString("WhyReason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s important to have a competent legal team at your side at the time of dire need. Legal processes are not only a hassle because you don’t understand legal terminologies but because there also not many firms that provide unparalleled expertise and consultation..
        /// </summary>
        public static string WhyReason2 {
            get {
                return ResourceManager.GetString("WhyReason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Clients Choose Us?.
        /// </summary>
        public static string WhyUs {
            get {
                return ResourceManager.GetString("WhyUs", resourceCulture);
            }
        }
    }
}
